name: dvora2goMetrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: workflow-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  theMatrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [2.7, 3.6, 3.8]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Matrix OS ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: echo ${{ matrix.os }} 

      - name: Matrix Version ${{ matrix.python-version }}
        if: matrix.os != 'windows-latest'
        run: echo ${{ matrix.python-version }}
