name: dvora2goMetrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: workflow-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  theMatrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [2.7, 3.6, 3.8]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Matrix OS ${{ matrix.os }}
        run: echo ${{ matrix.os }} 

      - name: RUNNER_TRACKING_ID
        run: echo $RUNNER_TRACKING_ID
        
      - name: Download all links from file - Macos
        if: matrix.os == 'macos-latest'
        run: |
          ls -la
          mkdir DownloadFiles
          brew install parallel
          cd ./DownloadFiles
          cat ../Downloads.txt | parallel --gnu "wget {}"

      - name: Get all Files Hashes - Macos
        if: matrix.os == 'macos-latest'
        shell: pwsh
        run: |
          $Results = Get-ChildItem ./DownloadFiles -File | Get-FileHash | Select -Property hash, @{N='File'; E={$_.path.split('/')[-1]}} 
          $Results | Export-Csv -Path ./macos_hash.csv -Encoding UTF8
          $Results

      - name: Download all links from file - Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          ls -la
          mkdir DownloadFiles
          cd ./DownloadFiles
          cat ../Downloads.txt | parallel --gnu "wget {}"

      - name: Get all Files Hashes - Linux
        if: matrix.os == 'ubuntu-latest'
        shell: pwsh
        run: |
          $Results = Get-ChildItem ./DownloadFiles -File | Get-FileHash | Select -Property hash, @{N='File'; E={$_.path.split('/')[-1]}} 
          $Results | Export-Csv -Path ./linux_hash.csv -Encoding UTF8
          $Results

